language: python
dist: xenial
python: '3.7'
install:
  - pip install -r requirements.txt

script:
# - mkdocs build
  - git clean -f -d -x
after_success:
  - git config user.name "Sergey Miroshnichenko"
  - git config user.email "serg.zorg@gmail.com"
  - git remote add gh-token "https://${GITHUB_TOKEN}@github.com/insales/insales-docs-source"
  - git fetch gh-token && git fetch gh-token gh-pages:gh-pages
  - mkdocs gh-deploy -v --clean --remote-name gh-token

env:
  matrix:
    secure: PfcWDKGgo1TkQuwt2SbLjHhLqnJRsJwjw+lkMpy/WAfAjJNQIYsSzfEzIv5N/BfsNZO7C3DLTD9GC7O5erw7YCK8zbhzmlQWgTo8cYFMnhhEhdE7XYC1DazJUj8V4dVw3Ts3aLO/waukvb8d/4eFsflauzF8O7YoQqCYBhpgzEdLQ72Fy7EMoRju4bdCLEg2zWXHx6QBcqT2bCGGkn2tgOW8+XfF+4T9Zea3kDLROufymK/soW8TaFZhz5lXxtCcwEASf6nBadLLTZV6Dgf3eOELxeJJUUmc3qho9DIwsxN7yQKwD78V3Oeevqq8BXTTNMHWObK8WRA9OOztQBHzyV4b+FIqwtSyM9O8vXD/nBn2lhvvryegxoy5BS4YR+zgV47Tkqv8tZb8c9cbpWLWDk4auTOSIzFoRY50ULDw3Mx4sPWjxP21twByRDz5h6DRbxQInDRMHenIFzviu6sBlFc5cdniollcsMk0Rj+DYp9SFqdDiUmd3bHWdKLxrVUykdOcBtRBpxmh8Tfwgxw4Aqx4HSHEwwttcpFIBqmGHO9TcsDR7b4oxgvFG19fT0SDrXUr4Ix/QP4yBY3IZoSR5RKfmHoc3DjFx7C6dEYsCGpVst4LqoexHiHUPhtk74+swuaLyW3zPxbH9vUlycv6lgAJd/qkWtD0tCzfr5X60f8=
